spring.application.name=labboot-back

# spring profiles
# spring.profiles.active='@xxx@'
# spring.profiles.validate=false

# Jackson
spring.jackson.date-format=yyyy-MM-dd
spring.jackson.time-zone=Asia/Taipei

# JPA
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.hibernate.naming.implicit-strategy=org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

# datasource
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.url=jdbc:sqlserver://host.docker.internal:9433;encrypt=true;trustServerCertificate=true;database=java;
spring.datasource.username=sa
spring.datasource.password=Wi$$4721s

# JsonWebTokenUtility
jwt.token.expire=10
